name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
          filename: 'release.zip'
          exclusions: '*.gitignore*'
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with: 
        token: ${{ secrets.TOKEN }}
        artifacts: "release.zip"
        tag: uwu
          



